web/controllers/account.py
from flask import Blueprint, flash, render_template, url_for, redirect
from flask_login import login_user, logout_user, login_required, current_user
from flask_rq import get_queue
from web.mail import send_email
from web.controllers.forms import *
from web.utils import *

account = Blueprint('account', __name__)


@account.route('/login', methods=['GET', 'POST'])
def login():
    """Log in an existing user."""
    form = LoginForm()
    if current_user.is_authenticated:
        flash('Already logged in. Want to log out?', 'info')
        return redirect(url_for('main.brother_portal'))

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.password_hash is not None and \
                user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash('You are now logged in. Welcome back!', 'success')
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('Invalid email or password.', 'form-error')
    return render_template('account/login.html', form=form)


@account.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.index'))


@account.route('/reset-password', methods=['GET', 'POST'])
def reset_password_request():
    """Respond to existing user's request to reset their password."""
    print(current_user)
    print(current_user.is_anonymous)
    if not current_user.is_anonymous:
        print('hey')
        return redirect(url_for('main.index'))
    form = RequestResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        print(user)
        print(form.email.data)
        if user:
            token = user.generate_password_reset_token()
            print(token)
            token = token.decode('utf-8')
            reset_link = url_for(
                'account.reset_password', token=token, _external=True)
            print(reset_link)
            send_email(
                recipient=user.email,
                subject='Reset Your Password',
                template='account/email/reset_password',
                user=user,
                reset_link=reset_link,
                next=request.args.get('next'))

            # get_queue().enqueue(
            #     send_email,
            #     recipient=user.email,
            #     subject='Reset Your Password',
            #     template='account/email/reset_password',
            #     user=user,
            #     reset_link=reset_link,
            #     next=request.args.get('next'))
        flash('A password reset link has been sent to {}.'.format(
            form.email.data), 'warning')
        return redirect(url_for('account.login'))
    return render_template('account/reset_password.html', form=form)

@account.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    """Reset an existing user's password."""
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    print('heh')
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('Invalid email address.', 'form-error')
            return redirect(url_for('main.index'))
        if user.reset_password(token, form.new_password.data):
            flash('Your password has been updated.', 'form-success')
            return redirect(url_for('account.login'))
        else:
            flash('The password reset link is invalid or has expired.',
                  'form-error')
            return redirect(url_for('main.index'))
    return render_template('account/reset_password.html', form=form)

web/controllers/search.py
from web import app

from flask import send_from_directory, request, redirect, render_template

import csv
import os

#@app.route('/search')
#def search():
#
#    csv_file = os.path.join(os.path.dirname(__file__), '..', 'assets', 'freshmen.csv')
#    print("Getting started")
#    freshmen = []
#
#    with open(csv_file, encoding='utf-8') as data:
#
#        reader = csv.reader(data, delimiter=',')
#
#        for freshman in reader:
#            profile = {
#                'name': freshman[0] + ' ' + freshman[1],
#                'email': freshman[2],
#                'phone': freshman[3]
#            }
#
#            freshmen.append(profile)
#
#    return render_template('search.html', freshmen=freshmen)

web/templates/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <!-- CSS -->
        <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='vendor/bootstrap.min.css')}}" >
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='web.css') }}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

        <!-- Fonts! -->
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">

        <!-- Javascript Libraries -->
        <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>

        <!-- Mobile -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta name="theme-color" content="#146eff">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="mobile-web-app-capable" content="yes">

        <!-- Favicon -->
        <link rel="icon" href="https://jk0uz2gof2j3u6upx2ef89l6-wpengine.netdna-ssl.com/wp-content/uploads/2015/04/favicon-small.png" type="image/png" sizes="16x16">
        <link rel="icon" href="https://jk0uz2gof2j3u6upx2ef89l6-wpengine.netdna-ssl.com/wp-content/uploads/2015/04/favicon-retina.png" type="image/png" sizes="32x32">
        <title>K&#931  &middot; {% block title %}{% endblock %}</title>
        
        
        {% block head %}
        {% endblock %}
    
        {% block meta %}
        {% endblock %}
    </head>

    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
            
            {% block end %}
            {% endblock %}
        </div>

        

        <script src="{{ url_for('static', filename='vendor/jquery-3.3.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendor/bootstrap.min.js') }}"></script>
    </body>
</html>

web/templates/home.html
{% extends 'layout.html' %}

{% block head %}
	<link rel=stylesheet type=text/css href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Home{% endblock %}

{% block nav %}
	<li class="nav-item"><a class="nav-link active" href="/about">About</a></li>
    {# <li class="nav-item"><a class="nav-link" href="/rush">Rush</a></li> #}
	{# <li class="nav-item"><a class="nav-link" href="/brothers">Brothers</a></li> #}
	<li class="nav-item"><a class="nav-link" href="/summer-housing">Summer Housing</a></li>
{% endblock %}

{% block page_content %}
	<section id="page_content">
		<div class="banner">
			<img src="static/img/ks.jpg" class="img-fluid" alt="Responsive image">
		</div>
		<div class="container-fluid">
			<div class="row justify-content-md-center">
				<div class="col-md-9 col-md-6">
					<div class="about">
					
						<h3>Kappa Sigma Gamma Pi Chapter</h3>
						<h5>MASSACHUSETTS INSTITUTE OF TECHNOLOGY</h5>
						<p>For more than a century, Kappa Sigma has shaped the lives of hundreds of MIT men by creating leaders on campus and in the world beyond.</p>

						<p>Located conveniently on West Campus between Baker and Burton Conner Houses, KΣ is right in the heart of the school. The house offers a welcoming and homely environment for brothers to work on assignments, eat delicious food, and have fun at MIT.</p>
						
						<p>Members of K&#931 are involved in all aspects of student life.  Whether as competitors on MIT's sports teams, members and leaders of student clubs, or friendly faces in class, K&#931 brothers continue to be positive influences on the MIT community.</p>
						
					</div>
				</div>
			</div>
		</div>
		<div class="video">
			<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/_rp5A7OzFYg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		</div>
	</section>

{% endblock %}

web/templates/layout.html
{% extends 'base.html' %}

{% block content %}
    <section id="layout">
        <div class="container-fluid">
            <nav class="navbar">
                <!-- Crest/Icon logo -->
                <a href="/" class="navbar-brand mr-auto">
                    <div class="logo">
                        <img src="/static/img/crest.png" />
                        <p>Kappa Sigma</p>
                    </div>
                </a>

                <!-- Collapse button -->
                <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
                    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="dark-blue-text"><i
                        class="fas fa-bars fa-1x"></i></span></button>
                
                <!-- Nav Options -->
                <div class="collapse navbar-collapse pull-right" id="navbarSupportedContent1">
                    <ul class="navbar-nav">
                        {% block nav %}
                        {% endblock %}
                    </ul>
                </div>
            </nav>

            <!-- Div for messages as they appear -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div  class="alert alert-{{category}}" role="alert" style="width:100%;">
                            {{ message }}
                            <button type="button" class="close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block page_content %}
            {% endblock %}
        </div>
    </section>

    <!-- Script to make it so you can delete the flash messages -->
    <script>
        $(document).on('click', '.close', function(){
            $(this).closest('div').remove();
        });
    </script>

    <footer class="footer mt-auto py-3">
        <div class="container">
            <div class="row">
                <div class="col-sm align-self-start left">
                    <p>407 Memorial Drive<br>Cambridge, MA 02139</p>
                </div>
                <div class="col-sm align-self-center center">
                    <img class="footer-image" src="/static/img/footer.png">
                </div>
                <div class="col-sm align-self-end right">
                    <p><a target="_none" rel="noopener" href="http://www.kappasigma.org">Kappa Sigma International</a><br>
                    <a target="_none" rel="noopener" href="http://studentlife.mit.edu/fsilg">MIT FSILG</a><br>
                    <a target="_none" rel="noopener" href="http://ifc.mit.edu/">MIT Interfraternity Council</a></p>
                </div>
            </div>
        </div>
    </footer>

{% endblock %}

web/templates/portal.html
{% extends 'layout.html' %}

{% block title %}Test{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link" href="/about">About</a></li>
	{# <li class="nav-item"><a class="nav-link" href="/rush">Rush</a></li> #}
	{# <li class="nav-item"><a class="nav-link" href="/brothers">Brothers</a></li> #}
	<li class="nav-item"><a class="nav-link" href="/summer-housing">Summer Housing</a></li>
	{% if current_user.is_authenticated %}
		<li class="nav-item"><a class="nav-link active" href="/brothers">Brothers Only</a></li>
		<li class="nav-item"><a class="nav-link" href="/settings">Profile</a></li>
	{% endif %}
{% endblock %}

{% block page_content %}
	<section id="page_content">
	<a href="{{ url_for('account.logout') }}">Logout</a>
        <h1>Welcome, {{ user.initials() }}</h1>
		<iframe src="https://calendar.google.com/calendar/embed?src=idtqlrq8mhtcbt7cudckv8f9k8%40group.calendar.google.com&ctz=America%2FNew_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
	</section>

{% endblock %}

web/templates/search.html
{% extends 'layout.html' %}

{% block head %}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Search{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link" href="/about">About</a></li>
<li class="nav-item"><a class="nav-link" href="/rush">Rush</a></li>
<li class="nav-item"><a class="nav-link active" href="/search">Search</a></li>
{# <li class="nav-item"><a class="nav-link" href="/brothers">Brothers</a></li> #}
<li class="nav-item"><a class="nav-link" href="/summer-housing">Summer Housing</a></li>
{% endblock %}

{% block page_content %}
<section id="page_content">
    <div style="max-width: 700px;margin: auto;">
        <h1>Freshmen Phone Number Search Tool</h1>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon">😎</span>
            </div>
            <input type="text" class="form-control" placeholder="Insert a name here..." aria-label="Freshman name"
                aria-describedby="addon" id="searchField">
            <div class="input-group-append">
                <button class="btn btn-outline-primary" type="button" onclick="search()">Search</button>
            </div>
        </div>
        <ul id="freshmen" class="list-group">
            {% for freshman in freshmen %}
            <li class="list-group-item" style="display:none;">
                <b>{{freshman.name}}</b>

                <div style="float: right;">
                    {% if freshman.phone | length %}
                    <span><a href="sms:{{freshman.phone}}">{{ freshman.phone }}</a></span>
                    {% else %}
                    <span>No Phone ☹️</span>
                    {% endif %}

                    {% if freshman.phone | length and freshman.email | length %}
                    <span> // </span>
                    {% endif %}

                    {% if freshman.email | length %}
                    <span><a href="mailto:{{ freshman.email }}?subject=Rush%20Kappa Sigma!&body=Hi {{freshman.name}}!">{{freshman.email}}</a></span>
                    {% endif %}
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>

<script src="{{ url_for('static', filename='script/search.js') }}"></script>

{% endblock %}

web/templates/summer-housing.html
{% extends 'layout.html' %}

{% block head %}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}Summer Housing{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link" href="/about">About</a></li>
{# <li class="nav-item"><a class="nav-link" href="/rush">Rush</a></li> #}
{# <li class="nav-item"><a class="nav-link" href="/brothers">Brothers</a></li> #}
<li class="nav-item"><a class="nav-link active" href="/summer-housing">Summer Housing</a></li>
{% endblock %}

{% block page_content %}
<section id="page_content">
    <div class="banner">
        <img src="static/img/summer.jpg" class="img-fluid" alt="Responsive image">
    </div>
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-8">
                <div class="about">

                    <h3>A Kappa Sig Summer</h3>
                    <h5>Summer Housing at Kappa Sigma</h5>

                    <p>
                    Every summer Kappa Sigma opens its doors for summer boarders. Located right on 
                    MIT campus in Cambridge and just a 364.4 smoot (+/- 1 ear) walk across the Harvard
                    Bridge to Boston, it's the perfect location for any person working or researching in Boston for
                    the summer.
                    </p>

                    {# 
                    <p>
                    Our application will soon be posted here, as well as with rental costs. In the meanwhile, just shoot an email to our <a href="mailto:ks-ec@mit.edu">Executive Committee</a> to begin the process of reserving your spot and getting more information.
                    </p>
                    #}

                    <p>
                    The application is currently online and available if you are interested in living with us for the summer. But, hurry though, rooms do go fast! Here is the link to  <a href="https://forms.gle/ewkrojbPUfFxHVJN6" target="_none" rel="noopener noreferrer">the application</a>. If you have any questions about living in Kappa Sig for the summer or need help with neural nets that misbehave, shoot an email to <a href="mailto:rmsander@mit.edu">Ryan Sander</a>, our Summer Housing Chair!
                    </p>

                    <p>
                    This information is in the application, but below are the prices for the different sorts of rooms that you can live in at Kappa Sigma this summer.
                    </p>

                    <ul>
                        <li><b>Single:</b> $2700</li>
                        <li><b>Double:</b> $2200</li>
                        <li><b>Quad:</b> $1900</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}